version: "2.0"
services:

  node-server:
    build: ./node
    container_name: node-server
    restart: always
    working_dir: /var/app
    volumes:
      - ../app:/var/app
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
    command: "npm start"