version: "2.0"
services:

  node-server-v2:
    # build: ./node
    image: node:14
    container_name: node-server-v2
    restart: always
    working_dir: /var/app
    volumes:
      - ../app:/var/app
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
    command: "npm run start"
    networks:
      - domotik-network

  # RabbitMq service
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.7-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbit"
      RABBITMQ_DEFAULT_PASS: "rabbit"
    networks:
      - domotik-network

networks:
  domotik-network:
    driver: bridge